### ISSUE TITLE
SIGSEGV in ioxsql tests after upgrade to Arrow v7

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/influxdb-iox-client-go#16]
#14 broke the `ioxsql` tests. This package's tests depend on a running instance of IOx, so it's hard to catch failures like this. I'll see if a newer version of arrow fixes the issue.

```
--- FAIL: TestNormalLifeCycle (0.03s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x10279603c]
...
github.com/influxdata/influxdb-iox-client-go/ioxsql.(*rows).Next(0x14000110180, {0x1400012c240, 0x2, 0x2})
        /Users/jacobmarble/projects/influxdb-iox-client-go/ioxsql/driver_rows.go:73 +0x70
...
github.com/influxdata/influxdb-iox-client-go/ioxsql_test.TestNormalLifeCycle(0x140002fe820)
        /Users/jacobmarble/projects/influxdb-iox-client-go/ioxsql/driver_test.go:106 +0x22c
...
FAIL    github.com/influxdata/influxdb-iox-client-go/ioxsql     0.262s
FAIL
```

_Originally posted by @jacobmarble in https://github.com/influxdata/influxdb-iox-client-go/issues/14#issuecomment-1064592858_

**Comment by wolffcm** [comment]
Like you I also tried to reproduce with the latest version of Arrow (they are already on `v8`, so I had to update the import paths in the cilent sources) but it still reproduces.

It looks like there is an `Allocator` that is set to `nil` in the Arrow code that is reading records off of the wire. I tried to explicitly set the allocator in the query request, and this fixed it:
```diff
diff --git a/ioxsql/driver.go b/ioxsql/driver.go
index fd52628..e81aa25 100644
--- a/ioxsql/driver.go
+++ b/ioxsql/driver.go
@@ -7,6 +7,7 @@ import (
        "errors"
        "strings"

+       "github.com/apache/arrow/go/v8/arrow/memory"
        "github.com/influxdata/influxdb-iox-client-go"
        "google.golang.org/grpc/connectivity"
 )
@@ -114,6 +115,7 @@ func (c *Connection) PrepareContext(ctx context.Context, query string) (driver.S
        if err != nil {
                return nil, err
        }
+       request = request.WithAllocator(memory.DefaultAllocator)
        return newStatement(request), nil
 }
```
The above code uses the new `v8`, but hopefully it will also work for `v7`. It seems like Arrow is often robust to `nil` allocators, so I wonder if this is an oversight in Arrow code.
