### ISSUE TITLE
Need to add wait for readable/wait for persisted logic to tests

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb-iox-client-go#23]
When I try to run this repo's tests against IOx NG, the queries are running before the ingester has gotten the data from the router. 

In IOx, we have some test helpers that [wait for the data to be readable](https://github.com/influxdata/influxdb_iox/blob/7b6754cc03ba551ac0033aa11fdd0af46402ad86/test_helpers_end_to_end_ng/src/steps.rs#L155-L163) or [wait for the data to be persisted](https://github.com/influxdata/influxdb_iox/blob/7b6754cc03ba551ac0033aa11fdd0af46402ad86/test_helpers_end_to_end_ng/src/steps.rs#L164-L172) before continuing, using the [write info service](https://github.com/influxdata/influxdb_iox/blob/7b6754cc03ba551ac0033aa11fdd0af46402ad86/generated_types/protos/influxdata/iox/ingester/v1/write_info.proto). This repo needs that logic too.

**Comment by alamb** [comment]
We could also fake it / hack it with a `sleep` temporarily 🤔  it would be dirty (but quick)

**Comment by carols10cents** [comment]
🧐

**Comment by alamb** [comment]
See https://github.com/influxdata/influxdb-iox-client-go/issues/27 for the actual need
