### ISSUE TITLE
Design and implement a client API to wait for writes to be visible

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb-iox-client-go#27]
# Usecase:
1. A client (e.g. a test in this repo, or a fluxtest in another repo) writes data to IOx NG
2. It wants to wait until the data is readable  (will appear in query results). See more details in the [lifecycle doc](https://docs.google.com/document/d/19fA0XtXHPBnBxB2yc6jFMu3cBnv1jsVpovbFL1NqVzc/edit#)

# Definition of Done:
1. Design the the changes to [influxdb-iox-client-go](https://github.com/influxdata/influxdb-iox-client-go) to support this usecase
2. Implement said API
3. Update tests to use this new API rather than sleep (which was done in https://github.com/influxdata/influxdb-iox-client-go/pull/25)

# Context
This is a follow on from @carols10cents 's original https://github.com/influxdata/influxdb-iox-client-go/issues/23

IOx OG has a "synchronous" write -- so when the write request returned was immediately readable. IOx NG has a different model where there is some time period between the write and when it will appear in subsequent reads (becomes "readable"). This is described in more details in the [lifecycle doc](https://docs.google.com/document/d/19fA0XtXHPBnBxB2yc6jFMu3cBnv1jsVpovbFL1NqVzc/edit#)

In order to write tests that don't have sleeps (such as https://github.com/influxdata/influxdb-iox-client-go/pull/25 and the internal `fluxtest`) we need to add a similar ability to influxdb-iox-client-go

The current equivalent in the other storage system is "get the current sequence number for partition" and then wait for this to be readable". Here is the internal logic for waiting for writes to TSM: https://github.com/influxdata/idpe/blob/master/internal/cmd/fluxtest/main.go#L372 

IOx NG has the same idea, though the number that is exposed today is per-write (in the write_info structure)

In IOx, we have some test helpers that [wait for the data to be readable](https://github.com/influxdata/influxdb_iox/blob/7b6754cc03ba551ac0033aa11fdd0af46402ad86/test_helpers_end_to_end_ng/src/steps.rs#L155-L163) or [wait for the data to be persisted](https://github.com/influxdata/influxdb_iox/blob/7b6754cc03ba551ac0033aa11fdd0af46402ad86/test_helpers_end_to_end_ng/src/steps.rs#L164-L172) before continuing, using the [write info service](https://github.com/influxdata/influxdb_iox/blob/7b6754cc03ba551ac0033aa11fdd0af46402ad86/generated_types/protos/influxdata/iox/ingester/v1/write_info.proto). This repo needs that logic too.

**Comment by carols10cents** [comment]
So currently the `WriteInfoService` that returns the status (readable, persisted) of a current write is [only implemented on the ingester](https://github.com/influxdata/influxdb_iox/blob/48d2fe1396343fdf536b5e0afe91494bb592801c/ingester/src/server/grpc.rs#L94). Are clients going to know about the existence of, and host/port of, ingesters? Or are clients only going to know about routers (where they send write requests) and queriers (where they send read requests)? In other words, should router2 and/or queriers also implement `WriteInfoService` somehow?

**Comment by alamb** [comment]
> Are clients going to know about the existence of, and host/port of, ingesters?

Short answer is I don't know

> In other words, should router2 and/or queriers also implement WriteInfoService somehow?

I suggest we implement `WriteInfoService` in the querier -- the rationale being that any client that wants to query will likely also want to be able to know when its data is readable.

Conveniently, the querier already has to know the ingester addresses in order to correctly execute queries, so no additional plumbing is needed

So perhaps we can implement `WriteInfoService` by having the queriers proxy the request to the ingesters. Something like

```text
                                   ┌───────────────┐   ┌───────────────┐                        
                                   │IOx Ingester 1 │   │IOx Ingester 2 │                        
                                   └───────────────┘   └───────────────┘                        
                                           ▲                   ▲                                
  1. Client includes optional                                                                   
  write token in request to                └ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘  2. Querier calls              
  querier                                           │             `WriteInfoService` for the    
                                                                  ingesters it knows about      
                                                    │                                           
┌─────────────┐                              ┌─────────────┐                                    
│   Client    │─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─▶│ IOx Querier │                                    
└─────────────┘                              └─────────────┘                                    
       ▲                                            │                                           
       │                                                                                        
        ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘                                           
                3. Querier consolidates response                                                
                and reports on readability /                                                    
                durability                                                                      
                                                                                                
```

Most of the code already exists for this:
* Configuration for querier to talk to ingesters: https://github.com/influxdata/influxdb_iox/blob/main/clap_blocks/src/querier.rs#L33-L39
* Client to make write info requests: https://github.com/influxdata/influxdb_iox/blob/main/influxdb_iox_client/src/client/write_info.rs
* Code to consolidate responses (currently in test helpers, but could be moved to the client crate): https://github.com/influxdata/influxdb_iox/blob/main/test_helpers_end_to_end_ng/src/client.rs#L210-L217


What do you think? Might make a nice little project in IOx

**Comment by jacobmarble** [comment]
> > Are clients going to know about the existence of, and host/port of, ingesters?
> 
> Short answer is I don't know

I hope not. The router should proxy everything.

> > In other words, should router2 and/or queriers also implement WriteInfoService somehow?
> 
> I suggest we implement `WriteInfoService` in the querier -- the rationale being that any client that wants to query will likely also want to be able to know when its data is readable.
> 
> Conveniently, the querier already has to know the ingester addresses in order to correctly execute queries, so no additional plumbing is needed
> 
> So perhaps we can implement `WriteInfoService` by having the queriers proxy the request to the ingesters.

I don't have an opinion here -- whatever makes the most sense.

**Comment by alamb** [comment]
I believe @carols10cents  plans to implement `WriteInfoService` in the querier by proxying to the ingester 👍
