### ISSUE TITLE
Upgrade to arrow v10

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb-iox-client-go#31]
arrow v8 has been released. Upgrading was included in #28 but that turns out to have causes problems when I tried to use the updated client in idpe (our internal code repo). Thus  we reverted the upgrade in #30

In order to update to arrow 8 we would need to update it in flux as well I think https://github.com/influxdata/flux 

I didn't see any open PRs to do so yet

More context is on  
https://github.com/influxdata/influxdb-iox-client-go/pull/30#issue-1235338690

**Comment by jacobmarble** [comment]
Now we need v10 (not released yet) for FlightSQL support. Flux probably shouldn't depend on a pre-release dependency, so we'll start [pre-release versioning this golang module](https://go.dev/doc/modules/version-numbers#pre-release) as v2.0.0-beta.X.
